"use client";
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {registerTools,object} from '@/lib/webmcp';
export default function Workbench(){const [local,setLocal]=useState('2026-11-01T01:30');const [zone,setZone]=useState('America/New_York');const [compare,setCompare]=useState('Europe/Madrid,Asia/Tokyo');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<unknown>({example:true,status:'ambiguous',message:'This local time occurs twice. Resolve it to see both instants.'});
 const resolve=useCallback(async(input:unknown)=>{const b=object(input);if(typeof b.local!=='string'||typeof b.zone!=='string'||(b.compare!==undefined&&(!Array.isArray(b.compare)||b.compare.some(x=>typeof x!=='string'))))throw Error('Provide local, zone, and optional comparison zones');const r=await fetch('/api/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const data=object(await r.json());if(!r.ok)throw Error(String(data.error));setLocal(b.local);setZone(b.zone);setCompare(((b.compare||[]) as string[]).join(','));setResult(data);return data;},[]);
 useEffect(()=>registerTools([{name:'resolve_local_time',description:'Resolve a local time to every matching UTC instant and display results. Does not access calendars, save the query, or publish a finding.',inputSchema:{type:'object',properties:{local:{type:'string'},zone:{type:'string'},compare:{type:'array',maxItems:6,items:{type:'string'}}},required:['local','zone'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:resolve}]),[resolve]);
 async function perform(){setBusy(true);setError('');try{await resolve({local,zone,compare:compare.split(',').map(x=>x.trim()).filter(Boolean)});}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="workbench"><section className="panel"><span className="step">LOCAL TIME → EXACT INSTANTS</span><label className="field"><span>Local date and time</span><Input type="datetime-local" value={local} onChange={e=>setLocal(e.target.value)} min="2000-01-01T00:00" max="2035-12-31T23:59"/></label><label className="field"><span>IANA time zone</span><Input value={zone} onChange={e=>setZone(e.target.value)} placeholder="America/New_York"/></label><label className="field"><span>Compare in these zones</span><Input value={compare} onChange={e=>setCompare(e.target.value)} placeholder="Europe/Madrid,Asia/Tokyo"/></label><Button disabled={busy} onClick={perform}>{busy?'Resolving…':'Resolve this time'}</Button><p className="muted">No calendar access or account. Inputs are processed for the response; this app does not save your scheduling queries.</p>{error&&<p role="alert" className="error">{error}</p>}</section><section className="panel result"><span className="step">RESULT / NO SILENT ASSUMPTIONS</span><pre aria-live="polite">{JSON.stringify(result,null,2)}</pre></section></div>;}
