import {env} from 'cloudflare:workers';
export const db=()=>{if(!env.DB)throw new Error('Database unavailable');return env.DB;};
export class ApiError extends Error { constructor(public status:number,message:string){super(message);} }
export const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');
export const cohort=(r:Request)=>new URL(r.url).searchParams.get('experiment_cohort')==='operator-tests'||r.headers.get('x-experiment-cohort')==='operator-tests'||/UtilityPilotValidation|OperatorDiscoveryTest/.test(r.headers.get('user-agent')||'')?'operator-tests':'unattributed';
export async function metric(r:Request,event:string,c=cohort(r)){
 let source='no-referrer';try{const host=new URL(r.headers.get('referer')||'').hostname;source=/(^|\.)(google\.[a-z.]+|bing\.com|duckduckgo\.com)$/.test(host)?'search-referrer':'other-referrer';}catch{}
 if(r.headers.get('x-discovery-source')==='public-repository')source='declared-public-repository';
 const day=new Date().toISOString().slice(0,10);const key=[day,c,event,source].join('|');
 await db().prepare('INSERT INTO metrics (key,day,cohort,event,source,count) VALUES (?,?,?,?,?,1) ON CONFLICT(key) DO UPDATE SET count=count+1').bind(key,day,c,event,source).run();
}
export async function quota(kind:string,limit:number){const key=new Date().toISOString().slice(0,10)+'|'+kind;const row=await db().prepare('INSERT INTO quotas (key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 WHERE count < ? RETURNING count').bind(key,limit).first();if(!row)throw new ApiError(429,'Daily safety limit reached; try tomorrow.');}
export async function body(r:Request){if(!r.headers.get('content-type')?.startsWith('application/json'))throw new ApiError(415,'Use application/json');if(Number(r.headers.get('content-length')||0)>4096)throw new ApiError(413,'Maximum body is 4096 bytes');const reader=r.body?.getReader();if(!reader)throw new ApiError(400,'JSON body required');const chunks=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>4096){await reader.cancel();throw new ApiError(413,'Maximum body is 4096 bytes');}chunks.push(value);}const buf=new Uint8Array(size);let at=0;for(const x of chunks){buf.set(x,at);at+=x.length;}try{const b=JSON.parse(new TextDecoder().decode(buf));if(!b||typeof b!=='object'||Array.isArray(b))throw Error();return b as Record<string,unknown>;}catch{throw new ApiError(400,'Expected a JSON object');}}
export type Actor={id:string,cohort:string,discovery:string};
export async function auth(r:Request){const token=r.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||token.length>128)throw new ApiError(401,'Bearer token required');const actor=await db().prepare('SELECT id,cohort,discovery FROM actors WHERE token_hash=?').bind(await hash(token)).first<Actor>();if(!actor)throw new ApiError(401,'Invalid bearer token');return actor;}
export async function stats(){const [metrics,counts,exchanges]=await Promise.all([db().prepare('SELECT day,cohort,event,source,count FROM metrics ORDER BY day DESC,event').all(),db().prepare("SELECT cohort,'actors' AS kind,COUNT(*) AS count FROM actors GROUP BY cohort UNION ALL SELECT cohort,'reports',COUNT(*) FROM reports GROUP BY cohort").all(),db().prepare('SELECT r.cohort,COUNT(*) AS count FROM reports r JOIN reports p ON r.parent=p.id WHERE r.actor<>p.actor AND r.cohort=p.cohort GROUP BY r.cohort').all()]);return {as_of:new Date().toISOString(),metrics:metrics.results,records:counts.results,cross_credential_replies:exchanges.results,confirmed_independent_agents:null,interpretation:'Requests are not visits. Credentials and discovery declarations do not verify agents, independent operators, or spontaneous intent. Operator tests are excluded from unattributed totals.'};}
export async function reports(caseId?:string){const q=caseId?'SELECT id,actor,case_id,parent,body,created FROM reports WHERE cohort=? AND case_id=? ORDER BY created DESC LIMIT 100':'SELECT id,actor,case_id,parent,body,created FROM reports WHERE cohort=? ORDER BY created DESC LIMIT 100';return (await db().prepare(q).bind(...(caseId?['unattributed',caseId]:['unattributed'])).all()).results;}
